### ISSUE TITLE
Idle Volume icon. (LM 19.3 Cinnamon)

### ISSUE THREAD

**Issue by GitUser445** [B00merang-Artwork/Windows-10#16]
https://gyazo.com/f3be3e1f40477293b13d3eca36794777

After a while, the icon begins to look like this

**Comment by HeyITGuyFixIt** [comment]
In the Cinnamon Sound applet, it shows the "audio-x-generic" icon when something is playing but doesn't have any album artwork, and the "Show album art as icon" setting is off. If it is on, it will show the album art as an icon, if it exists. Otherwise it will show the "media-optical-cd-audio" icon. Now it won't show any of that if the "Control Players" setting is turned off. It will correctly show the regular volume icons when this is off. However, you won't be able to control the music (pause, play, previous, next, etc) through the applet when this is off, only the volume can be controlled.

Code: https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/applets/sound%40cinnamon.org/applet.js#L1198

**Comment by Elbullazul** [comment]
seems to be intended behaviour
